services/WebAppSphereRemote/WebAppSphereRemote/Models/DeviceRegistry.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはテンプレートから生成されました。
//
//     このファイルを手動で変更すると、アプリケーションで予期しない動作が発生する可能性があります。
//     このファイルに対する手動の変更は、コードが再生成されると上書きされます。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppSphereRemote.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeviceRegistry
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public string DesiredProperties { get; set; }
        public string ReportedProperties { get; set; }
        public string ETags { get; set; }
        public string MethodName { get; set; }
        public string MethodPayload { get; set; }
        public string C2DMessage { get; set; }
    }
}

services/WebAppSphereRemote/WebAppSphereRemote/Controllers/DeviceRegistriesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebAppSphereRemote.Data;
using WebAppSphereRemote.Models;

namespace WebAppSphereRemote.Controllers
{
    public class DeviceRegistriesController : Controller
    {
        // private WebAppDeviceTestContext db = new WebAppDeviceTestContext();
        AzureIoTHubContext db = new AzureIoTHubContext();

        [Authorize(Users = "<- your facebook mail address ->")]
        // GET: DeviceRegistries
        public ActionResult Index()
        {
            //            return View(db.DeviceRegistries.ToList());
            return View(db.ToList());
        }

        // GET: DeviceRegistries/Details/5
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //            DeviceRegistry deviceRegistry = db.DeviceRegistries.Find(id);
            DeviceRegistry deviceRegistry = db.Find(id.Value);
            if (deviceRegistry == null)
            {
                return HttpNotFound();
            }
            return View(deviceRegistry);
        }

        // GET: DeviceRegistries/Create
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Create()
        {
            return View();
        }

        // POST: DeviceRegistries/Create
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Create([Bind(Include = "Id,DeviceId,DesiredProperties,ReportedProperties,ETags")] DeviceRegistry deviceRegistry)
        {
            if (ModelState.IsValid)
            {
                // db.DeviceRegistries.Add(deviceRegistry);
                // db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(deviceRegistry);
        }

        // GET: DeviceRegistries/Edit/5
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
//            DeviceRegistry deviceRegistry = db.DeviceRegistries.Find(id);
            DeviceRegistry deviceRegistry = db.Find(id.Value);
            if (deviceRegistry == null)
            {
                return HttpNotFound();
            }
            return View(deviceRegistry);
        }

        // POST: DeviceRegistries/Edit/5
        // 過多ポスティング攻撃を防止するには、バインド先とする特定のプロパティを有効にしてください。
        // 詳細については、https://go.microsoft.com/fwlink/?LinkId=317598 を参照してください。
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Edit([Bind(Include = "Id,DeviceId,DesiredProperties,ReportedProperties,ETags,MethodName")] DeviceRegistry deviceRegistry)
        {
            if (ModelState.IsValid)
            {
                //                db.Entry(deviceRegistry).State = EntityState.Modified;
                //              db.SaveChanges();
                db.Update(deviceRegistry);
                return RedirectToAction("Index");
            }
            return View(deviceRegistry);
        }

        string invokeMotorDrive(DeviceRegistry deviceRegistry)
        {
            string cmd = "";
            string speed = "150";
            switch (deviceRegistry.MethodName)
            {
                case "LF":
                    cmd = "LF" + speed;
                    break;
                case "LFRF":
                    cmd = "LF" + speed + ";" + "RF" + speed;
                    break;
                case "RF":
                    cmd = "RF" + speed;
                    break;
                case "LB":
                    cmd = "LB";
                    break;
                case "LBRB":
                    cmd = "LB;RB";
                    break;
                case "RB":
                    cmd = "RB";
                    break;
                case "LR":
                    cmd = "LR" + speed;
                    break;
                case "LRRR":
                    cmd = "LR" + speed + ";" + "RR" + speed;
                    break;
                case "RR":
                    cmd = "RR" + speed;
                    break;
            }
            string order = "{\"command\":\"" + cmd + "\"}";
            deviceRegistry.MethodName = "MotorDrive";
            deviceRegistry.MethodPayload = order;
            return db.Invoke(deviceRegistry);
        }

        [HttpPost]
        public ActionResult MotorDrive([Bind(Include ="Id,DeviceId,MethodName")] DeviceRegistry deviceRegistry)
        {
            string invocationResult = invokeMotorDrive(deviceRegistry);
            var listedDR = db.Find(deviceRegistry.Id);
            listedDR.MethodPayload = invocationResult;
            return RedirectToAction("Details", new { id = deviceRegistry.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult TriggerAlarm([Bind(Include ="Id,DeviceId")]DeviceRegistry deviceRegistry)
        {
            deviceRegistry.MethodName = "TriggerAlarm";
            deviceRegistry.MethodPayload="{\"msg\":\"hello\"}";
            string result = db.Invoke(deviceRegistry);
            var listedDR = db.Find(deviceRegistry.Id);
            listedDR.MethodPayload = result;
            return RedirectToAction("Details", new { id = deviceRegistry.Id });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Invoke([Bind(Include = "Id,DeviceId,MethodName,MethodPayload")] DeviceRegistry deviceRegistry)
        {
            var result = db.Invoke(deviceRegistry);
            DeviceRegistry listedDeviceRegistry = db.Find(deviceRegistry.Id);
            listedDeviceRegistry.MethodPayload = result;
            return RedirectToAction("Details", new { id = deviceRegistry.Id });
        }



        // POST: DeviceRegistries/Send/0
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Send([Bind(Include = "Id,DeviceId,C2DMessage")] DeviceRegistry deviceRegistry)
        {
            db.Send(deviceRegistry);
            return RedirectToAction("Details", new { id = deviceRegistry.Id });
        }

        // GET: DeviceRegistries/Delete/5
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            //            DeviceRegistry deviceRegistry = db.DeviceRegistries.Find(id);
            DeviceRegistry deviceRegistry = db.Find(id.Value);
            if (deviceRegistry == null)
            {
                return HttpNotFound();
            }
            return View(deviceRegistry);
        }

        // POST: DeviceRegistries/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Users = "<- your facebook mail address ->")]
        public ActionResult DeleteConfirmed(int id)
        {
   //         DeviceRegistry deviceRegistry = db.DeviceRegistries.Find(id);
//            db.DeviceRegistries.Remove(deviceRegistry);
  //          db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

services/WebAppSphereRemote/WebAppSphereRemote/Views/DeviceRegistries/Details.cshtml
@model WebAppSphereRemote.Models.DeviceRegistry

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>DeviceRegistry</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.DeviceId)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DeviceId)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.DesiredProperties)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.DesiredProperties)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ReportedProperties)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ReportedProperties)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ETags)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ETags)
        </dd>


    </dl>
</div>

<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |
    @Html.ActionLink("Back to List", "Index")
</p>
<h4>Motor Drive</h4>
<table>
    <tr>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "LF" })
                    <div class="form-group">
                        <input type="submit" value="Left Forward" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "LFRF" })
                    <div class="form-group">
                        <input type="submit" value="Both Forward" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "RF" })
                    <div class="form-group">
                        <input type="submit" value="Right Forward" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
    </tr>
    <tr>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "LB" })
                    <div class="form-group">
                        <input type="submit" value="Left Break" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "LBRB" })
                    <div class="form-group">
                        <input type="submit" value="Both Break" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "RB" })
                    <div class="form-group">
                        <input type="submit" value="Right Break" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
    </tr>
    <tr>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "LR" })
                    <div class="form-group">
                        <input type="submit" value="Left Reverse" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "LRRR" })
                    <div class="form-group">
                        <input type="submit" value="Both Reverse" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
        <td align="center">
            @using (Html.BeginForm("MotorDrive", "DeviceRegistries", FormMethod.Post))
            {
                <div>
                    @Html.HiddenFor(model => model.Id)
                    @Html.HiddenFor(model => model.DeviceId)
                    @Html.HiddenFor(model => model.MethodName, new { Value = "RR" })
                    <div class="form-group">
                        <input type="submit" value="Right Reverse" class="btn btn-default" />
                    </div>
                </div>
            }
        </td>
    </tr>
</table>
@using (Html.BeginForm("TriggerAlarm", "DeviceRegistries", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div>
        @Html.HiddenFor(model => model.Id)
        @Html.HiddenFor(model => model.DeviceId)
        <div class="form-group">
            <input type="submit" value="TriggerAlarm" class="btn btn-default" />
        </div>
    </div>
}
<h4>Method Invocation</h4>
@using (Html.BeginForm("Invoke", "DeviceRegistries", FormMethod.Post))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DeviceId)

        <div class="form-group">
            @Html.LabelFor(model => model.MethodName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MethodName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MethodName, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            @Html.LabelFor(model => model.MethodPayload, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.MethodPayload, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.MethodPayload, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Invoke" class="btn btn-default" />
            </div>
        </div>
    </div>
}
<h4>Send C2D Message</h4>
@using (Html.BeginForm("Send", "DeviceRegistries", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div>
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.DeviceId)

        <div class="form-group">
            @Html.LabelFor(model => model.C2DMessage, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.C2DMessage, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.C2DMessage, "", new { @class = "text-danger" })
            </div>
        </div>
        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Send" class="btn btn-default" />
            </div>
        </div>
    </div>
}

services/WebAppSphereRemote/WebAppSphereRemote/Views/DeviceRegistries/Edit.cshtml
@model WebAppSphereRemote.Models.DeviceRegistry

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
<div class="form-horizontal">
    <h4>DeviceRegistry</h4>
    <hr />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.Id)

    <div class="form-group">
        @Html.LabelFor(model => model.DeviceId, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DeviceId, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DeviceId, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.DesiredProperties, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.DesiredProperties, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.DesiredProperties, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ReportedProperties, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ReportedProperties, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ReportedProperties, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.ETags, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.ETags, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.ETags, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.MethodName, htmlAttributes: new { @class = "control-label col-md-2" })
        <div class="col-md-10">
            @Html.EditorFor(model => model.MethodName, new { htmlAttributes = new { @class = "form-control" } })
            @Html.ValidationMessageFor(model => model.MethodName, "", new { @class = "text-danger" })
        </div>
    </div>

    <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
            <input type="submit" value="Save" class="btn btn-default" />
        </div>
    </div>
</div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

services/WebAppSphereRemote/WebAppSphereRemote/Views/DeviceRegistries/Index.cshtml
@model IEnumerable<WebAppSphereRemote.Models.DeviceRegistry>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.DeviceId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.DesiredProperties)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ReportedProperties)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ETags)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.DeviceId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.DesiredProperties)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ReportedProperties)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.ETags)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.Id }) |
            @Html.ActionLink("Details", "Details", new { id=item.Id })
        </td>
    </tr>
}

</table>